# Generated by Django 4.2.4 on 2024-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_user_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeConsultationUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "Free Consultation Users",},
        ),
    ]
