# Generated by Django 4.2.4 on 2024-06-11 05:35

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0125_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="active_status",
            field=models.CharField(
                choices=[("disabled", "Disabled"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="iid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=30,
                prefix="ingred_",
                unique=True,
            ),
        ),
    ]
