# Generated by Django 4.2.4 on 2024-06-13 08:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_alter_ingredients_active_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="home_image",
            field=models.ImageField(
                default="home_img.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
