# Generated by Django 4.2.4 on 2024-06-13 09:06

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_category_home_page_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bhid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=22,
                        max_length=30,
                        prefix="main_cat",
                        unique=True,
                    ),
                ),
                ("banner_title", models.CharField(max_length=100)),
                (
                    "active_status",
                    models.CharField(
                        choices=[("disabled", "Disabled"), ("published", "Published")],
                        default="disabled",
                        max_length=10,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Banners and Sliders",},
        ),
    ]
