# Generated by Django 4.2.4 on 2024-06-13 09:15

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0129_bannerhome"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerhome",
            name="banner_image",
            field=models.ImageField(default="homebanner.jpg", upload_to="category"),
        ),
        migrations.AlterField(
            model_name="bannerhome",
            name="bhid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=30,
                prefix="bhid",
                unique=True,
            ),
        ),
    ]
