# Generated by Django 4.2.4 on 2024-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_alter_bannerhome_banner_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
