# Generated by Django 4.2.4 on 2024-06-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_category_category_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="productvariationtypes", name="product",),
        migrations.RemoveField(
            model_name="productvariationtypes", name="product_variation",
        ),
        migrations.RemoveField(
            model_name="productvariationtypesprices", name="product",
        ),
        migrations.RemoveField(
            model_name="productvariationtypesprices", name="product_variant_type",
        ),
        migrations.RemoveField(
            model_name="productvariationtypesprices", name="product_variation_types",
        ),
        migrations.DeleteModel(name="ProductVariation",),
        migrations.DeleteModel(name="ProductVariationTypes",),
        migrations.DeleteModel(name="ProductVariationTypesPrices",),
    ]
