# Generated by Django 4.2.4 on 2024-06-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_remove_product_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="yellow_peel",
            field=models.BooleanField(default=False),
        ),
    ]
