# Generated by Django 4.2.4 on 2024-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0136_productdescription_direction_for_use_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="status",),
        migrations.AddField(
            model_name="product",
            name="form",
            field=models.CharField(default="Liquid", max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(default="Dandruff Control...", max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Treseme..", max_length=500),
        ),
    ]
