# Generated by Django 4.2.4 on 2024-06-18 17:05

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_remove_product_status_product_form_product_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productvarient", name="have_variation",),
        migrations.RemoveField(model_name="productvarient", name="in_stock",),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[("disabled", "Disabled"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345678900",
                length=22,
                max_length=7,
                prefix="sku",
                unique=True,
            ),
        ),
    ]
