# Generated by Django 4.2.4 on 2024-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0138_remove_productvarient_have_variation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="courier_partner",
            field=models.CharField(
                choices=[("dtdc", "DTDC"), ("trackon", "Trackon")],
                default="trackon",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="tracking_id",
            field=models.CharField(default="145855..", max_length=100),
        ),
    ]
