# Generated by Django 4.2.4 on 2024-07-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_cartorder_courier_partner_cartorder_tracking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="youtube_link",
            field=models.CharField(default="1", max_length=12000),
        ),
    ]
