# Generated by Django 4.2.4 on 2024-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerhome",
            name="order",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
