# Generated by Django 4.2.4 on 2024-07-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_bannerhome_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="testimonials", name="testimonial_company",),
        migrations.RemoveField(model_name="testimonials", name="testimonial_image",),
    ]
