# Generated by Django 4.2.4 on 2024-07-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0143_remove_testimonials_testimonial_company_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PrivacyPolicy", new_name="InternationalShipping",
        ),
        migrations.RenameField(
            model_name="internationalshipping",
            old_name="privacy_policy_content",
            new_name="international_shipping_content",
        ),
    ]
