# Generated by Django 4.2.4 on 2024-07-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_rename_privacypolicy_internationalshipping_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internationalshipping",
            options={"verbose_name_plural": "International Shipping"},
        ),
    ]
