# Generated by Django 4.2.4 on 2024-07-14 16:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_alter_internationalshipping_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvarianttypes",
            old_name="varient_price",
            new_name="variant_price",
        ),
        migrations.AddField(
            model_name="productvarianttypes",
            name="variant_type_image",
            field=models.ImageField(
                default="productvarianttype.jpg",
                upload_to=core.models.user_directory_path,
            ),
        ),
    ]
