# Generated by Django 4.2.4 on 2024-07-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0146_rename_varient_price_productvarianttypes_variant_price_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvarianttypes",
            old_name="variant_price",
            new_name="varient_price",
        ),
    ]
