# Generated by Django 4.2.4 on 2024-07-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0148_productvarianttypes_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="productvarianttypes", name="user",),
        migrations.RemoveField(
            model_name="productvarianttypes", name="variant_type_image",
        ),
    ]
