# Generated by Django 4.2.4 on 2024-07-14 17:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0149_remove_productvarianttypes_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantTypeImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.models.product_variant_type_image_upload_path
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product_variant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.productvarianttypes",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Variant Type Images",},
        ),
    ]
