# Generated by Django 4.2.4 on 2024-07-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0150_productvarianttypeimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvarianttypeimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
            ),
        ),
    ]
