# Generated by Django 4.2.4 on 2024-07-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0151_productvarianttypeimages_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorder", options={"verbose_name_plural": "Cart Orders"},
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=99999),
        ),
    ]
