# Generated by Django 4.2.4 on 2024-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0152_alter_cartorder_options_alter_cartorder_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="invoice_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1", max_digits=99999),
        ),
    ]
