# Generated by Django 4.2.4 on 2024-07-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_cartorder_invoice_date_cartorder_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorder", options={"verbose_name_plural": "Cart Order"},
        ),
        migrations.RemoveField(model_name="cartorder", name="invoice_date",),
        migrations.RemoveField(model_name="cartorder", name="invoice_number",),
        migrations.RemoveField(model_name="cartorder", name="invoice_pdf",),
    ]
