# Generated by Django 4.2.4 on 2024-07-17 09:33

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0155_testimonials_testimonial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ccid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=22,
                        max_length=30,
                        prefix="concern_",
                        unique=True,
                    ),
                ),
                ("concern_title", models.CharField(max_length=100)),
                ("product_link", models.CharField(default="N/A", max_length=100)),
                (
                    "active_status",
                    models.CharField(
                        choices=[("disabled", "Disabled"), ("published", "Published")],
                        default="published",
                        max_length=10,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Shop By Concern",},
        ),
    ]
