# Generated by Django 4.2.4 on 2024-07-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0156_concern"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredients",
            old_name="meta_description",
            new_name="product_link",
        ),
        migrations.RemoveField(model_name="ingredients", name="banner_image",),
        migrations.RemoveField(model_name="ingredients", name="description",),
        migrations.RemoveField(model_name="ingredients", name="image",),
        migrations.RemoveField(model_name="ingredients", name="meta_tag",),
        migrations.RemoveField(model_name="ingredients", name="meta_title",),
    ]
