# Generated by Django 4.2.4 on 2024-07-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0157_rename_meta_description_ingredients_product_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="courier_partner",
            field=models.CharField(
                choices=[
                    ("not assigned", "NOT ASSIGNED"),
                    ("dtdc", "DTDC"),
                    ("trackon", "Trackon"),
                ],
                default="Not Assigned",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="tracking_id",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
