# Generated by Django 4.2.4 on 2024-07-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0160_cartorder_billingaddress_cartorder_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartorderitems", name="billingaddress",),
        migrations.RemoveField(model_name="cartorderitems", name="city",),
        migrations.RemoveField(model_name="cartorderitems", name="companyname",),
        migrations.RemoveField(model_name="cartorderitems", name="district",),
        migrations.RemoveField(model_name="cartorderitems", name="division",),
        migrations.RemoveField(model_name="cartorderitems", name="email",),
        migrations.RemoveField(model_name="cartorderitems", name="firstname",),
        migrations.RemoveField(model_name="cartorderitems", name="gstnumber",),
        migrations.RemoveField(model_name="cartorderitems", name="lastname",),
        migrations.RemoveField(model_name="cartorderitems", name="phone",),
        migrations.RemoveField(model_name="cartorderitems", name="pin_details",),
        migrations.RemoveField(model_name="cartorderitems", name="shippingaddress",),
        migrations.RemoveField(model_name="cartorderitems", name="state",),
        migrations.RemoveField(model_name="cartorderitems", name="zipcode",),
    ]
