# Generated by Django 4.2.4 on 2024-07-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0161_remove_cartorderitems_billingaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="gst_rates_final",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=5),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="price_wo_gst_total",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=99999),
        ),
    ]
