# Generated by Django 4.2.4 on 2024-07-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0162_cartorder_gst_rates_final_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitems",
            name="gst_rates_final",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="cartorderitems",
            name="price_wo_gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
